services:
    db:
        container_name: db-postgres
        image: postgres:15.2
        restart: always
        env_file:
            - ./backend/.env
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - horwatch-backend
      
    backend:
        build: ./backend
        container_name: horwatch-backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
        env_file:
            - ./backend/.env
    # frontend:
    #     build: ./frontend
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - ./frontend:/app
    #     depends_on:
    #         - backend
volumes:
    postgres_data:
networks:
    horwatch-backend:
    # howatch-frontend:
